# Generated by Django 3.0.6 on 2020-05-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Author')),
                ('song', models.TextField(max_length=2000, verbose_name='Song')),
                ('position', models.IntegerField(verbose_name='Position')),
            ],
        ),
    ]
