# Generated by Django 3.0.6 on 2020-05-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='author',
            field=models.TextField(max_length=2000, null=True, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='song',
            field=models.TextField(max_length=2000, null=True, verbose_name='Song'),
        ),
        migrations.AddField(
            model_name='musician',
            name='position',
            field=models.IntegerField(default=0, verbose_name='Position'),
        ),
    ]
